spring:
  datasource:
    url: jdbc:mysql://capstone2.cws2g2kqbmis.ap-northeast-2.rds.amazonaws.com:3306/capstone2  # RDS 엔드포인트와 DB 이름으로 수정
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DATABASE_USERNAME}  # MySQL 사용자 이름
    password: ${DATABASE_PASSWORD}  # MySQL 비밀번호
  jpa:
    hibernate:
      ddl-auto: update  # 필요에 따라 create, validate로 변경 가능
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect  # MySQL 8.x에 맞는 dialect 사용

server:
  port: 8080

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.engine.jdbc: DEBUG  # JDBC 연결 로그
